spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/star?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    tomcat:
      initial-size: 15
      max-wait: 2000
      max-active: 50
      max-idle: 50
      default-auto-commit: true
  jpa:
    properties:
      hibernate:
        use-new-id-generator-mappings: false
        enable_lazy_load_no_trans: true
        jdbc:
          time_zone: GMT+8